import type { AuditEvent } from "./types";

export const auditEvents: AuditEvent[] = [
  {
    id: 1,
    eventType: "quote-submitted",
    entityType: "quote",
    entityId: "Q-1003",
    title: "Q-1003 submitted",
    detail: "Estimator submitted quote Q-1003 for review.",
    actor: "Lena Ortiz",
    actorRole: "Estimator",
    timestamp: "10:42:15 AM",
    severity: "Info"
  },
  {
    id: 2,
    eventType: "approval-triggered",
    entityType: "quote",
    entityId: "Q-1003",
    title: "High-value approval triggered",
    detail: "Amount exceeded the owner approval threshold.",
    actor: "System",
    actorRole: "Automation",
    timestamp: "10:42:16 AM",
    severity: "Approval"
  },
  {
    id: 3,
    eventType: "owner-approved",
    entityType: "quote",
    entityId: "Q-1003",
    title: "Owner approved Q-1003",
    detail: "Owner / GM approved the quote after review.",
    actor: "Owner / GM",
    actorRole: "Approver",
    timestamp: "10:45:03 AM",
    severity: "Success"
  },
  {
    id: 4,
    eventType: "quote-converted",
    entityType: "quote",
    entityId: "Q-1003",
    title: "Q-1003 converted to J-2104",
    detail: "Quote was converted to active job J-2104.",
    actor: "Scheduler",
    actorRole: "Scheduler",
    timestamp: "10:46:11 AM",
    severity: "Automation"
  },
  {
    id: 5,
    eventType: "work-order-created",
    entityType: "workOrder",
    entityId: "WO-2104",
    title: "WO-2104 created",
    detail: "Routing generated from approved quote Q-1003.",
    actor: "System",
    actorRole: "Automation",
    timestamp: "10:46:12 AM",
    severity: "Automation"
  },
  {
    id: 6,
    eventType: "job-moved-production",
    entityType: "job",
    entityId: "J-2035",
    title: "J-2035 moved to production",
    detail: "Job released to the shop floor queue.",
    actor: "Scheduler",
    actorRole: "Scheduler",
    timestamp: "11:02:04 AM",
    severity: "Success"
  },
  {
    id: 7,
    eventType: "traveler-printed",
    entityType: "workOrder",
    entityId: "WO-2035",
    title: "Traveler printed for J-2035",
    detail: "Work order traveler generated for floor use.",
    actor: "Shop Supervisor",
    actorRole: "Supervisor",
    timestamp: "11:04:41 AM",
    severity: "Info"
  },
  {
    id: 8,
    eventType: "capacity-bottleneck-detected",
    entityType: "capacity",
    entityId: "Press Brake",
    title: "Press Brake bottleneck detected",
    detail: "Utilization exceeded 100 percent.",
    actor: "System",
    actorRole: "Automation",
    timestamp: "11:09:22 AM",
    severity: "Critical"
  },
  {
    id: 9,
    eventType: "scrap-logged",
    entityType: "quality",
    entityId: "J-2042",
    title: "Scrap logged for J-2042",
    detail: "Inspection recorded above tolerance scrap.",
    actor: "Quality Inspector",
    actorRole: "Quality",
    timestamp: "1:03:18 PM",
    severity: "Warning"
  },
  {
    id: 10,
    eventType: "scrap-approved",
    entityType: "quality",
    entityId: "J-2042",
    title: "Scrap approved for J-2042",
    detail: "Supervisor approved scrap disposition.",
    actor: "Supervisor",
    actorRole: "Supervisor",
    timestamp: "1:05:02 PM",
    severity: "Approval"
  },
  {
    id: 11,
    eventType: "rework-created",
    entityType: "quality",
    entityId: "RW-2042-01",
    title: "RW-2042-01 created",
    detail: "Rework order opened for weld porosity.",
    actor: "Quality Inspector",
    actorRole: "Quality",
    timestamp: "1:06:10 PM",
    severity: "Automation"
  },
  {
    id: 12,
    eventType: "material-shortage-detected",
    entityType: "material",
    entityId: "AL-6061-PLT-0.375",
    title: "Material shortage detected for J-2099",
    detail: "Available stock dropped below required quantity.",
    actor: "System",
    actorRole: "Automation",
    timestamp: "2:11:44 PM",
    severity: "Critical"
  },
  {
    id: 13,
    eventType: "purchase-request-created",
    entityType: "purchaseRequest",
    entityId: "PR-3091",
    title: "PR-3091 created",
    detail: "Purchase request opened for 50 sheets.",
    actor: "Purchasing",
    actorRole: "Purchasing",
    timestamp: "2:12:15 PM",
    severity: "Info"
  },
  {
    id: 14,
    eventType: "customer-report-generated",
    entityType: "report",
    entityId: "RPT-J-2035-CUSTOMER",
    title: "Customer status report generated for J-2035",
    detail: "Customer-safe report assembled for MetroFab Industries.",
    actor: "Customer Service",
    actorRole: "Support",
    timestamp: "3:01:08 PM",
    severity: "Info"
  },
  {
    id: 15,
    eventType: "customer-report-saved",
    entityType: "report",
    entityId: "RPT-J-2035-CUSTOMER",
    title: "Customer-safe report saved",
    detail: "Printable customer-safe version archived.",
    actor: "Customer Service",
    actorRole: "Support",
    timestamp: "3:01:14 PM",
    severity: "Success"
  }
];
