export function PrintFooter({
  preparedAt = "Today",
  version = "v1.0",
  generatedBy = "JobShop OS demo data"
}: {
  preparedAt?: string;
  version?: string;
  generatedBy?: string;
}) {
  return (
    <footer className="grid gap-2 border-t border-slate-200 pt-3 text-[11px] uppercase tracking-[0.16em] text-slate-500 sm:grid-cols-2 xl:grid-cols-4">
      <span>Generated by JobShop OS</span>
      <span>{generatedBy}</span>
      <span>Prepared {preparedAt}</span>
      <span>Traveler {version}</span>
    </footer>
  );
}
